use_frameworks!

target 'LeanCache_Example' do
  pod 'LeanCache', :path => '../'

  target 'LeanCache_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
